version: '3'
services:
  bossow-app:
    container_name: bossow
    build: .
    ports:
      - "5001:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: senhabossow
      MYSQL_DB: bossow
    depends_on:
      - mysql
    volumes:
      - .:/app
    networks:
      - flask-mysql

  mysql:
    container_name: bossow_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senhabossow
      MYSQL_DATABASE: bossow
      LANG: C.UTF-8
    command: --secure-file-priv='/var/lib/mysql-files'
    ports:
      - "3306:3306"
    networks:
      - flask-mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./images:/var/lib/mysql-files

networks:
  flask-mysql:
    driver: bridge
